server:
  port: 0
spring:
  application:
    name: reviews-kafka-consumer
  kafka:
    bootstrap-servers: localhost:9092
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO